# Generated by Django 4.2.7 on 2023-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees_ModelTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Mobilno', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=50)),
                ('Country', models.CharField(choices=[(' United States', ' United States'), ('Russia', 'Russia'), ('China', 'China'), ('India', 'India'), ('United Kingdom', 'United Kingdom'), ('South Korea', 'South Korea'), ('Pakistan', 'Pakistan'), ('Japan', 'Japan'), ('France', 'France')], max_length=50)),
                ('District', models.CharField(choices=[(' Punjab', ' Punjab'), ('Rajasthan', 'Rajasthan'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('munbai', 'munbai'), ('kerala', 'kerala')], max_length=50)),
                ('State', models.CharField(choices=[(' Chennai', ' Chennai'), ('Kanchipuram', 'Kanchipuram'), ('Kanyakumari', 'Kanyakumari'), ('Thoothukudi', 'Thoothukudi'), ('Coimbatore', 'Coimbatore'), ('madurai', 'mdurai')], max_length=50)),
                ('status', models.CharField(default='available', editable=False, max_length=50)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
