# Generated by Django 4.2.7 on 2023-11-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_ModelTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Date', models.DateField(max_length=50)),
                ('complaint', models.CharField(max_length=100)),
                ('status', models.CharField(default='available', editable=False, max_length=50)),
            ],
            options={
                'db_table': 'grievance',
            },
        ),
    ]
