# Generated by Django 4.2.7 on 2023-11-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_complaint_modeltable_eid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_modeltable',
            name='Mobilno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
