# Generated by Django 4.2.7 on 2023-12-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_complaint_modeltable_mobilno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_modeltable',
            name='eid',
        ),
    ]
