# Generated by Django 4.2.7 on 2023-12-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0005_remove_complaint_modeltable_eid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_modeltable',
            name='reply',
            field=models.CharField(default='Not Reply Yet', max_length=100, null=True),
        ),
    ]
