# Generated by Django 4.2.7 on 2023-12-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_complaint_modeltable_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_modeltable',
            name='empid',
            field=models.IntegerField(null=True),
        ),
    ]
