# Generated by Django 4.2.7 on 2023-12-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_complaint_modeltable_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_modeltable',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='complaint_modeltable',
            name='Mobilno',
        ),
    ]
